#!/usr/bin/env bash
set -eu

for icon_name in Icon Icon-maskable
do
  for pixels in 120 192 512
  do
    inkscape \
      -w $pixels \
      -h $pixels \
      -o $icon_name-$pixels.png \
      $icon_name.svg
  done
done

# 120 is needed for Google Drive OAuth only, so:
rm Icon-maskable-120.png
